# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.1
    container_name: db
    restart: always
    env_file: ../.env
    ports:
      - 1337:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

