# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.1
    container_name: db
    restart: always
    ports:
      - 1337:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 228
      POSTGRES_USER: user
      POSTGRES_DB: db

volumes:
  postgres_data:
